#!/usr/bin/env python3
"""
generate-context.py
Regenerates .agent/CONTEXT.md from current repo state.
Run by GitHub Actions on every merge to main.

Usage: python scripts/generate-context.py
Env vars: PROJECT_NAME, JIRA_PROJECT_KEY
"""

import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT         = Path(__file__).parent.parent
PROJECT_NAME = os.environ.get("PROJECT_NAME", "Project")
JIRA_KEY     = os.environ.get("JIRA_PROJECT_KEY", "PROJ")


def git_last_merge():
    result = subprocess.run(
        ["git", "log", "-1", "--pretty=format:%an · %ar"],
        capture_output=True, text=True
    )
    return result.stdout.strip() or "unknown"


def read_sprint():
    """Pull sprint name, end date, and task list from tasks/current-sprint.md.
    Expects first line: # Sprint NAME · ends YYYY-MM-DD
    """
    sprint_file = ROOT / "tasks" / "current-sprint.md"
    if not sprint_file.exists():
        return "No sprint file found", "unknown", []

    content = sprint_file.read_text()
    m = re.search(r"# Sprint (.+?) · ends (\S+)", content)
    sprint_name = m.group(1) if m else "Current sprint"
    sprint_end  = m.group(2) if m else "unknown"
    tasks = re.findall(r"- \[.\] .+", content)
    return sprint_name, sprint_end, tasks[:10]


def read_last_decisions(n=3):
    """Return last N decisions from docs/decisions/ sorted by filename date."""
    decisions_dir = ROOT / "docs" / "decisions"
    if not decisions_dir.exists():
        return []

    files = sorted(decisions_dir.glob("*.md"), reverse=True)[:n]
    results = []
    for f in files:
        date  = f.stem[:10]
        lines = f.read_text().splitlines()
        title = next((l.lstrip("# ") for l in lines if l.startswith("#")), f.stem)
        results.append(f"- {date} · {title} · docs/decisions/{f.name}")
    return results


def read_open_mode_a():
    """Return open/needs-follow-up rows from memory/quick-tasks.md."""
    qt_file = ROOT / "memory" / "quick-tasks.md"
    if not qt_file.exists():
        return []

    items = []
    for line in qt_file.read_text().splitlines():
        if "|" in line and ("open" in line.lower() or "needs-follow-up" in line.lower()):
            cols = [c.strip() for c in line.split("|") if c.strip()]
            if len(cols) >= 3:
                items.append(f"- {cols[0]} · {cols[1]} · {cols[2]}")
    return items[:5]


if __name__ == "__main__":
    now         = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sprint_name, sprint_end, tasks = read_sprint()
    decisions   = read_last_decisions()
    mode_a      = read_open_mode_a()

    task_block     = "\n".join(tasks)     if tasks     else "- No tasks found in current-sprint.md"
    decision_block = "\n".join(decisions) if decisions else "- No decisions recorded yet"
    mode_a_block   = "\n".join(mode_a)   if mode_a   else "- None"

    context = f"""<!-- AUTO-GENERATED by GitHub Actions. Do not edit manually. -->
<!-- Last updated: {now} -->

# {PROJECT_NAME} · context snapshot

## Status
- Sprint: {sprint_name} · ends {sprint_end}
- Last merge: {git_last_merge()}
- Open Mode A items: {len(mode_a)} (see memory/quick-tasks.md)

## Active sprint
{task_block}

## Last 3 decisions
{decision_block}

## Open Mode A items
{mode_a_block}

## For the agent
- Read .agent/project.md for client, stack, contacts
- Read .agent/instructions.md for standing rules
- Skills: .agent/skills/
- Memory: memory/MEMORY.md (do NOT use ~/.claude/ memory)
"""

    out = ROOT / ".agent" / "CONTEXT.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(context)
    print(f"CONTEXT.md written ({out.stat().st_size} bytes)")
